In [58]:
import pandas as pd
import pylab as plt
import analysis as an
import numpy as np

In [71]:
df = pd.read_csv("07-02-19.txt" ,sep = " ")
for field in fields:
    for frame in frames:

         i     x    y side  frame  field
0        0  1019   23   dx      0      0
1        1  1024   38   dx      0      0
2        2  1015   60   dx      0      0
3        3  1017   77   dx      0      0
4        4  1025   92   dx      0      0
5        5  1035  108   dx      0      0
6        6  1035  131   dx      0      0
7        7  1026  148   dx      0      0
8        8  1015  158   dx      0      0
9        9  1007  172   dx      0      0
10      10   998  188   dx      0      0
11      11   997  209   dx      0      0
12      12  1005  225   dx      0      0
13      13  1011  243   dx      0      0
14      14  1005  261   dx      0      0
15      15   986  260   dx      0      0
16      16   979  275   dx      0      0
17      17   985  296   dx      0      0
18      18   982  312   dx      0      0
19      19   969  324   dx      0      0
20      20   973  350   dx      0      0
21      21   983  360   dx      0      0
22      22   991  377   dx      0      0
23      23   987  396   dx      0      0
24      24   973  406   dx      0      0
25      25   953  408   dx      0      0
26      26   937  399   dx      0      0
27      27   920  405   dx      0      0
28      28   908  419   dx      0      0
29      29   903  439   dx      0      0
...     ..   ...  ...  ...    ...    ...
565270  70   917  342   sx    289     11
565271  71   919  338   sx    289     11
565272  72   921  334   sx    289     11
565273  73   924  330   sx    289     11
565274  74   929  328   sx    289     11
565275  75   936  327   sx    289     11
565276  76   941  328   sx    289     11
565277  77   943  332   sx    289     11
565278  78   942  337   sx    289     11
565279  79   945  340   sx    289     11
565280  80   951  339   sx    289     11
565281  81   951  343   sx    289     11
565282  82   954  347   sx    289     11
565283  83   959  348   sx    289     11
565284  84   965  349   sx    289     11
565285  85   971  347   sx    289     11
565286  86   977  345   sx    289     11
565287  87   982  344   sx    289     11
565288  88   986  345   sx    289     11
565289  89   988  346   sx    289     11
565290  90   990  349   sx    289     11
565291  91   991  353   sx    289     11
565292  92   990  357   sx    289     11
565293  93   988  363   sx    289     11
565294  94   986  370   sx    289     11
565295  95   984  377   sx    289     11
565296  96   983  383   sx    289     11
565297  97   984  388   sx    289     11
565298  98   985  393   sx    289     11
565299  99   989  397   sx    289     11

[565300 rows x 6 columns]

        field
0           0
1           0
2           0
3           0
4           0
5           0
6           0
7           0
8           0
9           0
10          0
11          0
12          0
13          0
14          0
15          0
16          0
17          0
18          0
19          0
20          0
21          0
22          0
23          0
24          0
25          0
26          0
27          0
28          0
29          0
...       ...
565270     11
565271     11
565272     11
565273     11
565274     11
565275     11
565276     11
565277     11
565278     11
565279     11
565280     11
565281     11
565282     11
565283     11
565284     11
565285     11
565286     11
565287     11
565288     11
565289     11
565290     11
565291     11
565292     11
565293     11
565294     11
565295     11
565296     11
565297     11
565298     11
565299     11

[565300 rows x 1 columns]